# Dockerfile used for creating a container capable to run AcmeAir monolithic
# Must be running on the same network as the mongodb container

ARG ACMEAIR_BASE

FROM ${ACMEAIR_BASE}

COPY --chown=1001:0 LibertyFiles/server.xml /config/server.xml
COPY --chown=1001:0 LibertyFiles/acmeair-java-2.0.0-SNAPSHOT.war /config/apps/
EXPOSE 9080
RUN features.sh

#ENV OPENJ9_SCC=false
ENV WARM_ENDPOINT=true
ENV VERBOSE=true
RUN configure.sh

